export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";

export const FETCH_REPO_DETAILS = "FETCH_REPO_DETAILS";
export const FETCH_REPO_DETAILS_SUCCESS = "FETCH_REPO_DETAILS_SUCCESS";
export const FETCH_REPO_DETAILS_FAILURE = "FETCH_REPO_DETAILS_FAILURE";
