export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";

export const FETCH_REPO_DETAILS = "FETCH_REPO_DETAILS";
export const FETCH_REPO_DETAILS_SUCCESS = "FETCH_REPO_DETAILS_SUCCESS";
export const FETCH_REPO_DETAILS_FAILURE = "FETCH_REPO_DETAILS_FAILURE";

export const ADD_TO_SEARCH_HISTORY = "ADD_TO_SEARCH_HISTORY";
export const ADD_TO_SEARCH_HISTORY_FAILURE = "ADD_TO_SEARCH_HISTORY_FAILURE";

export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
export const SET_SEARCH_TABLE_LOADING_STATE = "SET_SEARCH_TABLE_LOADING_STATE";

export const FETCH_SEARCH_HISTORY = "FETCH_SEARCH_HISTORY";
export const FETCH_SEARCH_HISTORY_SUCCESS = "FETCH_SEARCH_HISTORY_SUCCESS";
export const FETCH_SEARCH_HISTORY_FAILURE = "FETCH_SEARCH_HISTORY_FAILURE";
